# Generated by Django 3.1.3 on 2023-05-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
    ]
