# Generated by Django 3.1.3 on 2023-05-08 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aunctionItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 8, 50, 0, 559147, tzinfo=utc)),
        ),
    ]
