# Generated by Django 3.1.3 on 2023-05-08 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aunctionItem', '0002_auto_20230508_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
